FORMAT: 1A
HOST: https://warm-peak-72707.herokuapp.com

# API Viz
A (not so) Massive Online Repository for API Endpoints

## Authentication
This API uses OAuth v2 Bearer Token / Personal Access Token for its authentication.

# Endpoints [/endpoints]

## Endpoints GET ALL [GET]

+ Request (application/json)




+ Response 200 



## Endpoints POST [POST]

+ Request (application/json)

    + Attributes (Endpoints POSTRequest)


    + Body

            {
                "name": "venerator26",
                "fullUrl": "https://api.iextrading.com/1.0/stock/aapl/chart/5y?chartReset=true&randomParam=this",
                "parameters": [
                    {
                        "name": "period",
                        "value": "annual"
                    },
                    {
                        "name": "period",
                        "value": "annual"
                    }
                ]
            }


+ Response 200 




# Endpoints Username EndpointName [/endpoints/username/endpointName]

## Endpoints GET ONE [GET]

+ Request (application/json)




+ Response 200 




# Users [/users]

## Users POST [POST]

+ Request (application/json)

    + Attributes (Users POSTRequest)


    + Body

            {
                "fullname": "Full Name",
                "username": "username9000",
                "password": "anythingButPassword123"
            }


+ Response 200 




# Login [/login]

## Login POST [POST]

+ Request (application/json)

    + Attributes (Login POSTRequest)


    + Body

            {
                "fullname": "Full Name",
                "username": "username9000",
                "password": "anythingButPassword123"
            }


+ Response 200 




# Refresh [/refresh]

## Refresh POST [POST]

+ Request (application/json)

    + Attributes (Refresh POSTRequest)


    + Body

            {
                "fullname": "Full Name",
                "username": "username9000",
                "password": "anythingButPassword123"
            }


+ Response 200 




# Data Structures

## Endpoints POSTRequest (object)


### Properties
+ `name` (string, required) 
+ `fullUrl` (string, required) 
+ `parameters` (array[Parameter], required) 


## Parameter (object)


### Properties
+ `name`: `period` (string, required) 
+ `value`: `annual` (string, required) 


## Users POSTRequest (object)


### Properties
+ `fullname` (string, required) 
+ `username` (string, required) 
+ `password` (string, required) 


## Login POSTRequest (object)


### Properties
+ `fullname` (string, required) 
+ `username` (string, required) 
+ `password` (string, required) 


## Refresh POSTRequest (object)


### Properties
+ `fullname` (string, required) 
+ `username` (string, required) 
+ `password` (string, required) 

